[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["cd server && npx prisma generate"]

[start]
cmd = "cd server && npx prisma migrate deploy && node src/server.js"
