services:
  - type: web
    name: 3d-print-lab-api
    runtime: node
    region: frankfurt
    plan: free
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false          # задаётся вручную в Render Dashboard
      - key: JWT_SECRET
        generateValue: true  # Render генерирует автоматически
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://xbezumiex.github.io
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://xbezumiex.github.io/new_3d_printer_site
      - key: GOOGLE_CLIENT_ID
        value: 692826386412-ut7akn2ham1hpkogt3jifc26u0lo1div.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://threed-print-lab-api.onrender.com/api/auth/google/callback
      - key: GITHUB_CLIENT_ID
        value: Ov23liuDVLSsqzPkhVHo
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        value: https://threed-print-lab-api.onrender.com/api/auth/github/callback
